spring.application.name=tasks

spring.datasource.url=jdbc:postgresql://localhost:5432/springpractice
spring.datasource.username=postgres
spring.datasource.password=1810
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect